In [2]:
import numpy as np 
import pandas as pd 

In [4]:
list = [1,2,3,4,5]
list

[1, 2, 3, 4, 5]

In [6]:
np.array(list)

array([1, 2, 3, 4, 5])

In [7]:
list_2 = [[1,2,3],[4,5,6],[7,8,9]]
list_2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(list_2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,11, 2) #0 is start, 11 is end, 2 is step count

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.linspace(0,10,20) #20 is a count of array to get end number (10)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])